# Generated by Django 4.1.1 on 2022-09-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_chapter_work_id_fk_alter_chapter_work_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="description",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
