# Generated by Django 4.1.1 on 2022-09-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_chapter_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paragraph",
            name="character_id",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="work_id",
            field=models.CharField(max_length=32),
        ),
    ]
