# Generated by Django 4.1.1 on 2022-09-20 21:25

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_paragraph_character_id_alter_paragraph_work_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="paragraph",
            name="fts_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
