# Generated by Django 4.1.1 on 2022-09-20 21:26

from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_paragraph_fts_vector"),
    ]

    operations = [
        BtreeGinExtension(),
        TrigramExtension(),
    ]
