# Generated by Django 4.1.1 on 2022-09-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_product_id"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                  DROP TRIGGER IF EXISTS searchvector_update_trigger ON api_product;
                  CREATE OR REPLACE FUNCTION update_fts_vector()
                      RETURNS TRIGGER
                      LANGUAGE plpgsql AS
                  $$
                  BEGIN
                      SELECT setweight(to_tsvector(
                                              coalesce(NEW.product_name, '')), 'A'), -- Just name
                          setweight(to_tsvector(
                                              coalesce(NEW.product_description, '')), 'A'), -- Just description
                            setweight(to_tsvector(
                                              coalesce(NEW.product_name, '')), 'A') ||
                            setweight(to_tsvector(
                                              coalesce(NEW.product_description, '')), 'A') ||
                            setweight(to_tsvector(
                                              coalesce(NEW.brand, '')), 'B') ||
                            setweight(to_tsvector(
                                              coalesce(NEW.category_tree, '')), 'C') -- name & everything else.

                      INTO NEW.fts_vector_name, NEW.fts_vector_pd, NEW.fts_vector_all;
                      RETURN NEW;
                  END;
                  $$;

                  CREATE TRIGGER searchvector_update_trigger
                      BEFORE INSERT OR UPDATE OF product_description, product_name, fts_vector_name, fts_vector_pd, fts_vector_all
                      ON api_product
                      FOR EACH ROW
                  EXECUTE PROCEDURE update_fts_vector();

                  UPDATE api_product
                  SET fts_vector_all = NULL;
                """,
            reverse_sql="""
                      DROP TRIGGER IF EXISTS searchvector_update_trigger ON board_job;

                      DROP FUNCTION update_fts_vector();
                  """,
        ),
    ]
