# Generated by Django 4.1.1 on 2022-09-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_creating_trigger_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_specifications",
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
