# Generated by Django 4.1.1 on 2022-09-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_product_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category_tree",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
